### ISSUE TITLE
Pubblicare la piattaforma in riuso su Developers Italia

### ISSUE THREAD

**Issue by fpietrosanti** [dipartimentofunzionepubblica/partecipa#1]
Obiettivo di questo ticket è Pubblicare la piattaforma in riuso su Developers Italia integrando e sviluppando https://github.com/italia/publiccode.yml

**Comment by libremente** [comment]
Ciao @fpietrosanti, in questo momento la piattaforma risulta essere correttamente pubblicata su https://developers.italia.it/it/software/pcm-dipartimentofunzionepubblica-partecipa però magari ti riferisci ad altre integrazioni

**Comment by maintainer-partecipa** [comment]
Facendo seguito a quanto già segnalato da @libremente, la piattaforma è riutilizzabile dall’attuale sito. Il file publiccode.yml è regolarmente pubblicato nella root del progetto.
