### ISSUE TITLE
Aggiornamento del publiccode.yml per riuso Regione Emilia-Romagna

### ISSUE THREAD

**Issue by lucacatti** [dipartimentofunzionepubblica/partecipa#10]
Buongiorno,
si richiede l'aggiornamento del file in oggetto in seguito all'adozione tramite riuso del sistema da parte di Regione Emilia-Romagna.
Grazie!

**Comment by lucacatti** [comment]
Per il codice IPA:
https://www.indicepa.gov.it/ipa-portale/consultazione/responsabile-transizione-digitale/ricerca-responsabile-transizione-digitale/scheda-ente/22002

**Comment by Jeanluc74** [comment]
Buon pomeriggio,

siamo in attesa di un feed-back su publiccode.yml prima di procedere.

Appena avremo riscontro vi aggiorneremo qui.

**Comment by Jeanluc74** [comment]
Abbiamo aggiornato il publiccode.yml indicando Regione Emilia-Romagna sotto usedBy. Attendiamo  di riscontrare l'aggiornamento nel catalogo riuso.

**Comment by maintainer-partecipa** [comment]
Gli aggiornamenti sono regolarmente pubblicati nel catalogo del riuso
