### ISSUE TITLE
Modulo decidim-comparative_stats non sembra funzionare

### ISSUE THREAD

**Issue by turlando** [dipartimentofunzionepubblica/partecipa#11]
Buonasera,

sto usando l'ultima versione di Partecipa ([ef15985](https://github.com/dipartimentofunzionepubblica/partecipa/commit/ef15985911d6a1d494f37ef2c2bc2c102326b9a9)) e ho riscontrato due problemi con il modulo decidim-comparative_stats.

Il primo, meno grave, consiste nell'assenza della traduzione italiana per gli elementi nel pannello di amministrazione, come è possibile vedere nel seguente screenshot.

![screenshot_2022-08-31_18:54:37](https://user-images.githubusercontent.com/645191/187735912-ea46fdba-c141-401d-8a86-23d450aab35d.png)

Il secondo problema, più grave, è che provando ad inserire l'endpoint della installazione locale di Partecipa, come indicato nella documentazione del modulo, ottengo un errore HTTP 500. Ho [aperto una issue](https://github.com/Platoniq/decidim-module-comparative_stats/issues/33) nel repository del modulo dove sono presenti ulteriori informazioni sul problema.

È un problema della mia installazione o è un problema noto?

**Comment by Jeanluc74** [comment]
Buongiorno,

rispondo punto per punto:

1) sì al momento manca la localizzazione italiana per il modulo decidim-comparative_stats. E' necessario richiederla utilizzando crowdin e poi eseguire le traduzioni. E' un task che cercheremo di chiudere a breve. Al momento se si vuole aggirare l'ostacolo e utilizzare la localizzazione inglese basta copiare il file https://github.com/Platoniq/decidim-module-comparative_stats/blob/master/config/locales/en.yml sotto la root della gem /config/locales/en.yml in /config/locales/it.yml. Poi occorre editare la seconda riga sostituendo "en" con "it". 
Se invece il modulo non serve basta commentarlo dal Gemfile e rifare bundle.

2) per ottenere le statistiche di un tenant (sempre che siano pubblicate dallo stesso) occorre aggiungere un endpoint nella pagina da lei indicata sopra, ad es. l' URL di Barcellona é https://www.decidim.barcelona/api. Non dovrebbero esserci problemi, l'URL si costruisce aggiungendo al baseURL dell'applicativo /api. Se funziona correttamente con Barcellona e non con un altro URL presumibilmente è solo una questione di raggiungibilità dell'URL che lei tentava di configurare.

**Comment by Jeanluc74** [comment]
Buon pomeriggio,

il problema segnalato al punto 1) sopra è stato risolto includendo nel repository di ParteciPa la localizzazione italiana di decidim-comparative_stats, in attesa che venga integrata nella gem stessa. Per ottenere l'aggiornamento deve fare un git pull del master di ParteciPa, dovrebbe ottenere il commit https://github.com/dipartimentofunzionepubblica/partecipa/commit/61cbf94702cf2741c640959a7b16c2d034e5f10d .

**Comment by turlando** [comment]
Buongiorno,

la ringrazio per la celere risposta e per aver prontamente integrato la localizzazione italiana del modulo nel repository.

A una più attenta analisi il secondo problema presentato, cioè l'errore 500 in fase di inserimento di una organizzazione, sembra derivare dalla configurazione di rete dell'ambiente, presumibilmente dovuto a una mancata risoluzione DNS dell'hostname relativo all'endpoint.

Pertanto reputo che la issue possa essere considerata risolta.
