### ISSUE TITLE
Lista ID provider per accesso SPID incompleta

### ISSUE THREAD

**Issue by wbigger** [dipartimentofunzionepubblica/partecipa#12]
Per accedere al sito di ParteciPa nella tendina SPID non compaiono tutti gli identity provider, in particolare mancano:
- InfoCert
- TeamSystem ID

[Lista dei provider accreditati](https://www.agid.gov.it/it/piattaforme/spid/identity-provider-accreditati).

La pagina da cui sto provando a fare l'accesso è:
- [https://partecipa.gov.it/users/sign_in](https://partecipa.gov.it/users/sign_in)

**Comment by Jeanluc74** [comment]
Lista aggiornata, grazie della segnalazione.
