### ISSUE TITLE
Accesso con CIE mancante

### ISSUE THREAD

**Issue by wbigger** [dipartimentofunzionepubblica/partecipa#13]
Dalla [pagina di login](https://partecipa.gov.it/users/sign_in) manca la possibilità di accedere tramite CIE (Carta Identità Elettronica).

**Comment by Jeanluc74** [comment]
L'accesso con CIE, attraverso PUA (Punto Unico di Accesso) del Dipartimento Funzione Pubblica, è ora presente. Solo per chiarezza: si tratta di uno sviluppo che era già in fase avanzata di test al momento in cui è stata aperta questa segnalazione.
