### ISSUE TITLE
Dockerfile per semplificare lo start up

### ISSUE THREAD

**Issue by alessiomaddaluno** [dipartimentofunzionepubblica/partecipa#14]
Salve, la mia amministrazione stava valutando per alcuni casi specifici l'utilizzo di ParteciPA.
Considerando che il progetto Decidim offre dei Dockerfile e docker-compose.yml che semplifica al massimo lo startup del servizio, volevo sapere se era stato pensato anche per questo fork del progetto anche per chi  vorrebbe preoccuparsi di testare l'applicazione e non è decisamente ferrato in ambiente Ruby. 

Grazie.

**Comment by maintainer-partecipa** [comment]
Buongiorno, 

non esiste al momento supporto per Docker all'interno del progetto ParteciPa. 
Per testare Decidim in modo immediato invece, e avere un'idea di base delle funzionalità della piattaforma, è possibile avvalersi di una installazione condivisa di test messa a disposizione dai maintainer della piattaforma che risponde alla URL https://try.decidim.org. 
Per installare ParteciPa è possibile utilizzare le istruzioni dettagliate per sistema operativo che sono fornite alla URL https://platoniq.github.io/decidim-install ricordando che ParteciPa è una development app di Decidim e in quanto tale va installata con git clone https://github.com/dipartimentofunzionepubblica/partecipa in luogo della installazione di Decidim vera e propria che nella guida è indicata al p.to "3. Installing Decidim" con il comando gem install decidim . 
Decidim é una dipendenza di ParteciPa contenuta all'interno del Gemfile di ParteciPa. Si veda il README.md del progetto e il file FAQ.md richiamato nel README.md stesso. 
In caso di necessità di chiarimenti su specifici passaggi contattateci su maintainer-partecipa@formez.it .

Cordiali saluti.
