### ISSUE TITLE
Aggiornamento del publiccode.yml per riuso Regione Autonoma della Sardegna – Codice IPA r_sardeg

### ISSUE THREAD

**Issue by pres-sistemi** [dipartimentofunzionepubblica/partecipa#15]
Si richiede l'aggiornamento del file publiccode.yml  indicato nell’oggetto in seguito all'adozione tramite riuso del sistema ParteciPa da parte della Regione Autonoma della Sardegna con codice IPA: r_sardeg e pubblicato alla URL [https://sardegnapartecipa.regione.sardegna.it/](https://urlsand.esvalabs.com/?u=https%3A%2F%2Fsardegnapartecipa.regione.sardegna.it%2F&e=a92d5d13&h=a5e41fdc&f=y&p=y)

**Comment by maintainer-partecipa** [comment]
Aggiornato il pubbliccode.yml, andrà presumibilmente pubblicato sul catalogo riuso https://developers.italia.it/it/software/pcm-dipartimentofunzionepubblica-partecipa domani.
