### ISSUE TITLE
NoMethodError: undefined method `pathname' for #<#<Class:0x00005598debc0850>:0x00005598dea9cc30>

### ISSUE THREAD

**Issue by pkirk** [dipartimentofunzionepubblica/partecipa#16]
Gentili,
ho provato l'installazione, ultimo rbenv da git, 
rbenv install 2.7.0; rbenv local 2.7.0
gem install bundler:2.2.18
git clone https://github.com/dipartimentofunzionepubblica/partecipa.git
cd partecipa; bundle install

tutto liscio ma su 
bundle exec rails assets:precompile
ottengo il seguente errore

`/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:68: warning: already initialized constant Net::ProtocRetryError
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:214: warning: already initialized constant Net::BufferedIO::BUFSIZE
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/net-protocol-0.2.1/lib/net/protocol.rb:541: warning: already initialized constant Net::NetPrivate::Socket
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/2.7.0/net/protocol.rb:503: warning: previous definition of Socket was here
DeprecatedDSL will be removed from GraphQL-Ruby 2.0, use .to_non_null_type instead of '!' and remove '.activate' from /webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/bundler/gems/decidim-04ca5ebdba87/decidim-core/lib/decidim/core/engine.rb:89:in block in <class:Engine>'
Creating scope :with_attached_avatar. Overwriting existing method Decidim::User.with_attached_avatar.
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant Decidim::User::PrivacySettingsAssociationExtension
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of PrivacySettingsAssociationExtension was here
Creating scope :for_user. Overwriting existing method Decidim::Moderation.for_user.
Creating scope :in_review. Overwriting existing method Decidim::Comments::Comment.in_review.
Creating scope :not_in_review. Overwriting existing method Decidim::Comments::Comment.not_in_review.
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/associations/builder/collection_association.rb:27: warning: already initialized constant Decidim::User::PrivacySettingsAssociationExtension
/webapps/decidim/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/activerecord-6.0.6.1/lib/active_record/associations/builder/collection_association.rb:27: warning: previous definition of PrivacySettingsAssociationExtension was here
Creating scope :for_user. Overwriting existing method Decidim::Moderation.for_user.
Creating scope :in_review. Overwriting existing method Decidim::Comments::Comment.in_review.
Creating scope :not_in_review. Overwriting existing method Decidim::Comments::Comment.not_in_review.
Creating scope :with_attached_avatar. Overwriting existing method Decidim::UserGroup.with_attached_avatar.
rails aborted!
NoMethodError: undefined method pathname' for #<#<Class:0x00005598debc0850>:0x00005598dea9cc30>
Did you mean?  path_to_image

Tasks: TOP => assets:precompile
(See full trace by running task with --trace)`

**Comment by pkirk** [comment]
Downgrade di sprockets alla 3.5.2 sembra aver risolto.

**Comment by Jeanluc74** [comment]
Il problema potrebbe essere legato a webpacker. 
Dalla versione 0.25.2 che integra Rails 6 Decidim utilizza purtroppo webpacker in luogo di sprockets per la gestione degli assets (immagini, css, javascript). Sprocrets rimane supportato come alternativa a webpacker da Rails 6 ma dovrebbe essere utilizzato webpacker, non abbiamo mai testato la compatibilità di sprockets con questa versione di Decidim.
Quindi occorre disporre nella macchina dei seguenti software ed eseguire i seguenti comandi, si veda anche la pagina https://github.com/dipartimentofunzionepubblica/partecipa/blob/master/FAQ.md :
1) Installare NodeJs: versione 16.9.x (versione obbligatoria);
2) Installare Npm: versione: 7.21.x (versione minima);
3) npm i;
4) bundle exec rails webpacker:install ;
5) bundle exec rails decidim:webpacker:install ;
6) bundle exec rails webpacker:compile ;
Con l'ultimo comando il sistema dovrebbe compilare gli assets, i precedenti dal 1) al 5) servono per metterlo in condizioni di farlo.
Fare riferimento anche a questa pagina https://docs.decidim.org/en/develop/develop/guide_migrate_webpacker_app.html che espone come migrare, in quel caso, una instance app di Decidim, che è ciò che è ParteciPa, a webpacker e Rails 6.
