### ISSUE TITLE
Riuso Città Metropolitana di Cagliari

### ISSUE THREAD

**Issue by lmilia** [dipartimentofunzionepubblica/partecipa#17]
Si chiede l'inserimento della Città Metropolitana di Cagliari, codice IPA cmdca, tra gli enti riutilizzatori della piattaforma

**Comment by Jeanluc74** [comment]
OK, modificato il file publiccode.yml . Grazie

**Comment by lmilia** [comment]
perfetto



Da:     "glcorso" ***@***.***>
Per:    "dipartimentofunzionepubblica/partecipa" 
***@***.***>
Cc:     "lmilia" ***@***.***>, "Author" 
***@***.***>
Data:   19/03/2024 13:56
Oggetto:        Re: [dipartimentofunzionepubblica/partecipa] Riuso Città 
Metropolitana di Cagliari (Issue #17)



OK, modificato il file publiccode.yml . Grazie
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>
