### ISSUE TITLE
Aggiungere supporto a RSS

### ISSUE THREAD

**Issue by amreo** [dipartimentofunzionepubblica/partecipa#3]
Dato che voglio essere parte della cittadinanza attiva, mi piacerebbe poter visionare e dare la mia opinione su tutte le consultazioni. Per farlo ho bisogno di essere sempre aggiornato sulle ultime consultazioni pubblicate.
Mi piacerebbe che il software pubbliccasse tramite [RSS](https://en.wikipedia.org/wiki/RSS) (e mostrasse il relativo pulsante) tutte le nuove consultazione e tutte le modifiche apportate alle consultazioni affinché io tramite il mio aggregatore RSS preferito possa vedere le novità!

**Comment by maintainer-partecipa** [comment]
La ringraziamo del suggerimento, al momento RSS non è previsto nella roadmap del progetto ParteciPa ma la sua inclusione potrà essere oggetto di valutazioni future.
