### ISSUE TITLE
Impossibile usare la piattaforma senza SPID anche per soli scopi di test - la precompilazione sembra impossibile senza i parametri di Spid 

### ISSUE THREAD

**Issue by pboscolo0660** [dipartimentofunzionepubblica/partecipa#5]
Chiedo se è possibile ottenere una versione del sito senza SPID (e quindi senza dover definire tutti gli elementi di SPID) agendo sulla configurazione. Provando solo a commentare i moduli nel Gemfile non basta.

Sarei intenzionato a testare la piattaforma e vorrei evitare di fare tutto quanto necessario per far precompilare il tutto con i dati per SPID.

Se non è possibile al momento penso che un'opzione del genere dovrebbe essere prevista.

**Comment by maintainer-partecipa** [comment]
Ci scusiamo per il ritardo nella risposta, non dipendente dalla nostra volontà.
E' possibile disabilitare Spid, e il corrispondente menù "Entra con Spid", tramite la costante SPID_ENABLED valorizzata a "false" nel file application.yml. 
In questo caso non è necessario né indicato agire sul Gemfile.
Dalla versione taggata v0.2 il sistema non richiede che siano presenti i files di configurazione relativi a Spid, i metadata e i certificati, nel caso di SPID_ENABLED="false" Spid viene del tutto bypassato ed è possibile usare ParteciPa senza averlo predisposto.

**Comment by maintainer-partecipa** [comment]
Chiudo la issue, nel caso riscontri ancora problemi potrà riaprirla.
