### ISSUE TITLE
Bad copy for page footer links

### ISSUE THREAD

**Issue by riffraff** [dipartimentofunzionepubblica/partecipa#6]
The FAQ and ToS pages are empty and titled "default title for X".

Since they also show up on the footer in the homepage this is pretty ugly, I understand that there may not be any content for FAQs yet, but we can at least fix the title. 

Lack of ToS is more embarassing,  I can sign up and accept an empty ToS. 

<img width="602" alt="Screenshot 2021-06-22 at 07 56 08" src="https://user-images.githubusercontent.com/37493/122871555-7e405100-d32f-11eb-8c64-d2f211b4b666.png">

**Comment by maintainer-partecipa** [comment]
Thank you for raising this issue. We decided to temporarily disable the English version. It will be activated soon, with a complete set of translations.
