### ISSUE TITLE
Dichiarazione e livello di accessibilità della piattaforma

### ISSUE THREAD

**Issue by jdeyla** [dipartimentofunzionepubblica/partecipa#8]
Buongiorno,
esiste una dichiarazione di accessibilità di questa piattaforma partecipativa? Esiste una verifica fatta da qualcuno? grazie

**Comment by maintainer-partecipa** [comment]
La dichiarazione di accessibilità della piattaforma è stata pubblicata su https://form.agid.gov.it/view/a729e5ad-d32d-44f5-ad07-3bf0f41a66d5/
